export default {

  SIGN_UP: 'SIGN_UP',
  // LOG_IN: 'LOG_IN',
  // FETCH_SINGLE_REQUEST: 'FETCH__SINGLE_REQUEST',
  // FETCH_ALL_REQUESTS: 'FETCH_ALL_REQUESTS',
  // DELETE_REQUEST: 'DELETE_REQUEST',
  // POST_REQUEST: 'POST_REQUEST',
  // RESET_REQUEST: 'RESET_REQUEST',

};
