export default {

  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UPFAILURE',
  LOG_IN_SUCESS: 'LOG_IN_SUCESS',
  LOG_IN_FAILURE: 'LOG_IN_FAILURE',
  // FETCH_SINGLE_REQUEST: 'FETCH__SINGLE_REQUEST',
  // FETCH_ALL_REQUESTS: 'FETCH_ALL_REQUESTS',
  // DELETE_REQUEST: 'DELETE_REQUEST',
  // POST_REQUEST: 'POST_REQUEST',
  // RESET_REQUEST: 'RESET_REQUEST',

};
